package com.remotefalcon.api.enums;

public enum StatusResponse {
  SHOW_EXISTS,
  EMAIL_NOT_VERIFIED,
  EMAIL_CANNOT_BE_SENT,
  SHOW_NOT_FOUND,
  UNAUTHORIZED,
  INVALID_JWT,
  API_ACCESS_REQUESTED,
  UNEXPECTED_ERROR;
}
