const sequences = [
  {
    sequenceKey: 51095,
    remoteToken: 'abc123',
    sequenceName: 'All I Want for Christmas Is You',
    sequenceDisplayName: 'Mariah Carey - All I Want for Christmas Is You',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-07T08:32:03-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 1,
    sequenceOrder: 1,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51096,
    remoteToken: 'abc123',
    sequenceName: 'Last Christmas',
    sequenceDisplayName: 'Taylor Swift - Last Christmas',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T07:16:40-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 2,
    sequenceOrder: 2,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51097,
    remoteToken: 'abc123',
    sequenceName: 'Ho Ho Ho (And a Bottle of Rum)',
    sequenceDisplayName: 'Sia - Ho Ho Ho (And a Bottle of Rum)',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T07:09:17-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 3,
    sequenceOrder: 3,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51101,
    remoteToken: 'abc123',
    sequenceName: 'Twelve Days of Christmas',
    sequenceDisplayName: 'Relient K - Twelve Days of Christmas',
    sequenceDuration: 30,
    sequenceVisible: false,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:59:08-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 4,
    sequenceOrder: 4,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51103,
    remoteToken: 'abc123',
    sequenceName: "It's the Most Wonderful Time of the Year",
    sequenceDisplayName: "Andy Williams - It's the Most Wonderful Time of the Year",
    sequenceDuration: 30,
    sequenceVisible: false,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51104,
    remoteToken: 'abc123',
    sequenceName: 'Some Command',
    sequenceDisplayName: 'Some Command',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'COMMAND',
    sequenceGroup: null
  },
  {
    sequenceKey: 51107,
    remoteToken: 'abc123',
    sequenceName: 'PSA 1',
    sequenceDisplayName: 'PSA 1',
    sequenceDuration: 30,
    sequenceVisible: false,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51108,
    remoteToken: 'abc123',
    sequenceName: 'PSA 2',
    sequenceDisplayName: 'PSA 2',
    sequenceDuration: 30,
    sequenceVisible: false,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: true,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51105,
    remoteToken: 'abc123',
    sequenceName: 'White Christmas',
    sequenceDisplayName: 'Bing Crosby - White Christmas',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: false,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'SEQUENCE',
    sequenceGroup: null
  },
  {
    sequenceKey: 51106,
    remoteToken: 'abc123',
    sequenceName: 'Set Volume',
    sequenceDisplayName: 'Set Volume',
    sequenceDuration: 30,
    sequenceVisible: true,
    sequenceVotes: 0,
    sequenceVoteTime: '2022-10-13T06:57:34-05:00',
    sequenceVotesTotal: 0,
    sequenceIndex: 5,
    sequenceOrder: 5,
    sequenceImageUrl: '',
    isSequenceActive: false,
    ownerVoted: false,
    sequenceVisibleCount: 0,
    sequenceType: 'COMMAND',
    sequenceGroup: null
  }
];

export default sequences;
